---
title: Interactive Web Applications with Shiny. An intuition.
author: Michael Fuchs
date: '2018-10-19'
slug: interactive-web-applications-with-shiny-an-intuition
categories:
  - R
tags:
  - R Markdown
output: html_document
runtime: shiny
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
```
#Table of Content

+ 1 Introduction
+ 2 

#1 Introduction






Für diesen Post wurde der Datensatz *IMDB-Movie-Data* von der Statistik Plattform ["Kaggle"](https://www.kaggle.com) verwendet. Eine Kopie des Datensatzes ist unter <https://drive.google.com/open?id=13ytotLAXb70lgYHnblPbUWr9cb2z7SaN> abrufbar.

```{r results='hide', message=FALSE, warning=FALSE}
movie <- read_csv("IMDB-Movie-Data.csv")
```

#2 Preparation
```{r}
movie %>% separate(Genre, into = c("main genre", "further genre1", "further genre2")) %>% 
  select(Genre = `main genre`, Titel = Title, Spielfilmlänge = `Runtime (Minutes)`, Bewertung = Rating,     Wählerstimmen = Votes, Einnahmen = `Revenue (Millions)`, Metascore) -> movie2
```



```{r}
ui <- fluidPage(
  
  
  sidebarLayout(
    
    
    sidebarPanel(
      
      
      selectInput(inputId = "y", 
                  label = "Y-axis:",
                  choices = c("Spielfilmlänge", "Bewertung", "Wählerstimmen", "Einnahmen", "Metascore"), 
                  selected = "Bewertung"),
      
      
      selectInput(inputId = "x", 
                  label = "X-axis:",
                  choices = c("Spielfilmlänge", "Bewertung", "Wählerstimmen", "Einnahmen", "Metascore"), 
                  selected = "Spielfilmlänge"),
      
      
      selectInput(inputId = "z", 
                  label = "Color by:",
                  choices = c("Bewertung", "Genre"),
                  selected = "Genre")
    ),
    
    
    mainPanel(
      plotOutput(outputId = "scatterplot")
    )
  )
)


server <- function(input, output) {
  
  
  output$scatterplot <- renderPlot({
    ggplot(data = movie2, aes_string(x = input$x, y = input$y,
                                     color = input$z)) +
      geom_point()
  })
}


```



shinyApp(ui = ui, server = server)











