---
title: Choosing the correct statistical test in R
author: Michael Fuchs
date: '2018-10-04'
slug: choosing-the-correct-statistical-test-in-r
categories:
  - R
tags:
  - R Markdown
---

In diesem Post soll zusammengefasst werden, unter welchen Umständen welcher (statistische) Test anzuwenden ist. 

+ **Mittelwertsvergleiche**


| **Fragestellung**-      | **Normalverteilung**-   | **Varianzhomogenität** | **Test**  |
| :------------- | :----------: | :----------: |----------: |
|  Vergleich von zwei Gruppen  aus einer Stichprobe | ja   | ja |  ["T-Test"](https://michael-fuchs.netlify.com/2018/09/12/t-test/) für unabhängige Stichproben |
| s.o.   |  ja | nein    |  Welch Test |
| s.o.   | nein | nein    |  ["Wilcoxon Test"](https://michael-fuchs.netlify.com/2018/10/04/nonparametric-methods/) |
| Vergleich von mehr als zwei Gruppen aus einer Stichprobe | ja | ja    |  einfaktorelle Varianzanalyse (["ANOVA"](https://michael-fuchs.netlify.com/2018/09/13/anova/)) ohne Messwiederholung  |
| s.o.   | ja | nein    |  One-way-Test (Welch)  |
| s.o.   | nein | nein    |   ["Kruskal Wallis Test"](https://michael-fuchs.netlify.com/2018/10/04/nonparametric-methods/) |


+ **Zusammenhangsmaße** 

| **Skalierung** | **Test**  |
| :------------- | ----------: |
| zwei metrische Variablen: | ["Person's r"](https://michael-fuchs.netlify.com/2018/09/04/bivariate-descriptive-statistics/)    |
| eine metrisch & eine ordinalskalierte Variable:       | ["Spearman's roh"](https://michael-fuchs.netlify.com/2018/09/04/bivariate-descriptive-statistics/)  |
| zwei ordinalskalierte Variablen: |  ["Kendall's tau"](https://michael-fuchs.netlify.com/2018/09/04/bivariate-descriptive-statistics/)    |
| zwei nominalskalierten Vaiablen: | ["Chi^2^ Test"](https://michael-fuchs.netlify.com/2018/10/04/nonparametric-methods/)  |

Anmerkung: ist eine metrisch skalierte Variable nicht normalverteilt, so muss  das Zusammenhangsmaß mit niedrigerer Güte berechnet werden. 


+ **Beziehungen zwischen unterschiedlichen Variablen**

| **Prädiktor**       | **Kriterium**     | **Test** |
| :------------- | :----------: | ----------: |
| ein metrischer   |  ein metrisches | ["Bivariate lineare Regression"](https://michael-fuchs.netlify.com/2018/09/21/regression-analysis/) | 
| zwei metrische   |  ein metrisches |  ["Multiple lineare Regression"](https://michael-fuchs.netlify.com/2018/09/21/regression-analysis/) | 
| ein metrischer + eine Moderatorvariable (metrisch)   | ein metrisches |  ["Moderierte Regression"](https://michael-fuchs.netlify.com/2018/10/02/special-regression-analysis/)  | 
| kategorial + metrisch   |  ein metrisches | ["Kovarianzanalyse"](https://michael-fuchs.netlify.com/2018/10/02/special-regression-analysis/)  | 
| ein metrischer   |  ein kategoriales |   ["Logistische Regression"](https://michael-fuchs.netlify.com/2018/10/02/special-regression-analysis/)  | 


+ **Sonstige**

| **Test auf**       | **Test**     |
| :------------- | ----------: |
| Normalverteilung   |  ["Lilliefors-Test"](https://michael-fuchs.netlify.com/2018/09/12/t-test/)|
| Varianzhomogenität   |  ["Levene Test"](https://michael-fuchs.netlify.com/2018/09/12/t-test/) |
| Identifikation von Outliern   |  ["Grubbs Test"](https://michael-fuchs.netlify.com/2018/09/22/identification-of-outliers/)|


